### ISSUE TITLE
Is it possible to await a terminal command?

### ISSUE THREAD

**Issue by JetErorr** [jeff-hykin/macro-commander#12]
I'm trying to automate cleaning a flutter project and then start debugging (F5),
Is there a way to wait for the 'workbench.action.terminal.sendSequence' to complete and then execute the new one in the list? 

e.g.:

"macros": {
        "Flutter Clean" : [
            "workbench.action.terminal.new",
            {
                "command": "workbench.action.terminal.sendSequence", 
                "args": { "text": "aScriptToCleanTheProject" }
            },
            "debug.startFromConfig",
        ]
    },

Thanks!

**Comment by jeff-hykin** [comment]
Sadly it's probably not possible in way you want it to be. This extension `await`'s all commands. The initial problem is that the sendSenquece doesn't wait for a command to finish. Actually sending a sequence doesn't even know if you're sending a command, you could just be sending characters for autocomplete or you could be sending multiple commands.

To get around this I created the hidden console `"hiddenConsole" : "echo $userInput"`,  which should wait for the command to finish before doing the next command. However, it has the side effect of obviously not being visible.

Knowing if a command is sent/finished in a user-visible cross-platform console is pretty hard (from VS Code's perspective or anyone's perspective really). You can make a hack to get around this by sending two commands, the actual command followed by a signal (like creating a done.txt file), then have the next macro-command wait for the signal (continually look for the done.txt).

**Comment by JetErorr** [comment]
I can use hiddenConsole as console visibility isn't really required. 

Also, the 'observe for a file change' hack seems good if I needed to go that way. 

Thanks!
