### ISSUE TITLE
Execute VSCode Command Help

### ISSUE THREAD

**Issue by super-tomcat** [jeff-hykin/macro-commander#16]
Hi, i created a Macro to open a new Terminal, start Steel Bank Common Lisp, and then Start a Server with Port number (3 commands in the Terminal)... this works fine, however after i have executed those commands i also need to execute a command to call an extensions command, the command normally opens the Command Palette asks me what port number to use (defaults to the same port number used earlier) to which i normally just press Return and then a new window opens that connects me to the Lisp REPL, however i am having trouble sending the Command Palette command, please see the macro here....

```

 "macros": {
                "StartSBCLWithServer": [
                    // a simple command to open a new terminal
                    "workbench.action.terminal.new",
                    // a command with arguments, that sends text to the terminal, the \u000D is Return
                    {
                    "command": "workbench.action.terminal.sendSequence", 
                    "args": { "text": "SBCL\u000D (ql:quickload :swank)\u000D (swank:create-server)\u000D" }
                    },
                    // The above works fine, but this is the command i am having trouble executing, it calls a command in another
                   // extension called Alive.....
                   
                    "vscode.commands.executeCommand('alive.attachRepl')",
                   
 ] 
```

**Comment by jeff-hykin** [comment]
So it looks like you're trying to run JavaScript on that last one (the `"vscode.commands.executeCommand('alive.attachRepl')",`)

Instead of a string replace it with something like this 

```
{
    "javascript": [
        "vscode.commands.executeCommand('alive.attachRepl')", 
    ]
},
```

**Comment by jeff-hykin** [comment]
I'm going to close this but feel free to keep the conversation going
