### ISSUE TITLE
How to pass values for commands that require them?

### ISSUE THREAD

**Issue by Levaru** [jeff-hykin/macro-commander#22]
I want to execute a macro that will first change the indentation from 2 to 4 spaces and then reindent the lines. My current macro looks like this:

```
"indentFile": [
    "editor.action.indentUsingSpaces",
    "editor.action.reindentlines"
]
```

My problem is that the command `editor.action.indentUsingSpaces` opens an input box to enter the amount of spaces. How can I change the macro, so that a default value will be inserted and only then the `editor.action.reindentlines` command will be executed?

**Comment by jeff-hykin** [comment]
So, this is how to pass arguments in general:

```jsonc
[
        "editor.action.indentUsingSpaces",
        {
            "command": "editor.action.reindentlines", 
            "args": { "text": "1\n" }
        },
]
```

However the `"text": "1\n"` part I'm unsure about. You'll have to look up the VS code API for reindentlines to see what the argument name is (e.g. replace `text` with something else). Sadly searching the VS Code API isn't the easiest thing in the world, but that's beyond my control.

**Comment by Levaru** [comment]
This is what I tried to do, based on the examples. First of all, the commands should be in a different order, because it's `editor.action.indentUsingSpaces` that opens up an input window:

```
[
        {
            "command": "editor.action.indentUsingSpaces", 
            "args": { "text": "1\n" }
        },
        "editor.action.reindentlines"
]
```

I looked at the source code of VSCode and found the relevant action [IndentUsingSpaces](https://github.com/microsoft/vscode/blob/5e74da62da14652f024b0198af40641861a864b4/src/vs/editor/contrib/indentation/browser/indentation.ts#L281) which extends [ChangeIndentationSizeAction](https://github.com/microsoft/vscode/blob/5e74da62da14652f024b0198af40641861a864b4/src/vs/editor/contrib/indentation/browser/indentation.ts#L209).

`ChangeIndentationSizeAction` uses some variables like `tabSize` and `indentSize`. I tried both of them but nothing worked. At this point I'm stuck. I'm not really familiar with how VSCode works but could it be that this action just doesn't take any arguments and needs the user to input something?

**Comment by jeff-hykin** [comment]
Yeah sadly its pretty hard overall to find out how to use the VS Code API.

I know some pretty basic stuff is problematic. For example theres a "toggleRegexFindOption" ... but there's no way of checking to see if the regex option is already on or already off. Toggle is the only action. 

If you're really determined though, you can use the Javascript API to manually perform the indenting. You'd start at something like

```js
((async ()=>{
    const editor = vscode.window.activeTextEditor
    for (const selection of editor.selections) {
        const selectedText = editor.document.getText(selection)
        editor.edit((builder) => {
             builder.replace(selection, result)
        })
    }
})())
```

**Comment by Levaru** [comment]
Thank you for the javascript suggestion! I solved my problem with this macro:

```
"indentFile": [
            {
                "javascript": [
                    "const editor = vscode.window.activeTextEditor;",
                    "const pickedVal = 4;",
                    "editor.options['tabSize'] = pickedVal;",
                ]
            },
            "editor.action.reindentlines"
        ]
```
