### ISSUE TITLE
question on how to use it or is it a limitation ?

### ISSUE THREAD

**Issue by maindoor** [jeff-hykin/macro-commander#24]
Is it possible to write a macro through macro-commander to switch to the last used buffer in one go:
      "switchbuffer": [
          "workbench.action.showEditorsInActiveGroup",
          "cursorDown", <this doesn't seem to work, all I need is an arrow down key to be pressed">
          "Enter"
      ]

Then I can assign a keyboard short-cut for this macro.

**Comment by jeff-hykin** [comment]
I'm not sure what you're trying to accomplish, I don't really know what you mean by buffer. That said, the extension exposes all of the VS Code API, so if it is possible with the API, then it's possible with this extension. 

My guess is you might need to do something like focus on the active document using JavaScript before a command like cursorDown will do anything.

**Comment by maindoor** [comment]
got my answer. it should be                 "workbench.action.quickOpenNavigateNextInEditorPicker"
