### ISSUE TITLE
undo command id

### ISSUE THREAD

**Issue by martinakos** [jeff-hykin/macro-commander#25]
I'm trying to write a macro that evaluates the selected commented code in to the debug console. This is what I have so far:

```
    "macros": {
        "evaluate_comment": [            
            "editor.action.commentLine",
            "editor.debug.action.selectionToRepl",
            "undo"
        ]
    }
```

The command id for Undo (Ctrl-Z) is just "undo" according to the keybindings. 
However, I guess just "undo" is the wrong command, because the first two steps work but the undo doesn't.  

Any idea how could I solve this issue? Maybe issuing a "Crtl+Z" sequence (corresponding to undo) ?  I'm not sure if that's possible.

**Comment by jeff-hykin** [comment]
I'm going to close this since it doesn't really change/affect the macro-commander extension
