### ISSUE TITLE
Force serialize executions

### ISSUE THREAD

**Issue by cdhagmann** [jeff-hykin/macro-commander#27]
```
"macros": {
  "Silly Example": [
    "workbench.action.terminal.new",
    {
      "command": "workbench.action.terminal.sendSequence",
      "args": { "text": "sleep 10\n" }
    },
    "workbench.action.terminal.killAll",
  ],
},
"Less Silly Example": [
    "workbench.action.some_other_extension.stop_app",
    "workbench.action.terminal.new",
    {
      "command": "workbench.action.terminal.sendSequence",
      "args": { "text": "docker compose down\n" }
    },
    {
      "command": "workbench.action.terminal.sendSequence",
      "args": { "text": "docker compose up -d\n" }
    },
    "workbench.action.some_other_extension.start_app",
  ],
},
```

This silly example results in a new terminal blinking into existence before being killed despite the sleep command still being active.

The real world use case is that sometimes my docker container breaks and I have to stop the application, stop and start the docker containers, and then start my application up again. But again, the application doesn't wait for the docker containers to be back up.

**Comment by jeff-hykin** [comment]
I don't think there's any good way the extension can handle this. It is just sending text to the terminal so it can't know if a command finished or not.

You could make a wrapper around it though. This is just pseduocode (probably won't run), but should explain what I mean:

```jsonc
    {
      "command": "workbench.action.terminal.sendSequence",
      "args": { "text": "touch .docker_still_running; docker compose down; rm -f .docker_still_running;\n" }
    },
    "replaceAllExample1": [
        {
            "javascript": [
                "const fs = require('fs')",
                "if (fs.syncExists(".docker_still_running)) {",
                "    await vscode.commands.executeCommand('workbench.action.terminal.killAll'); ",
                "}"
            ],
        },
    ],
```

**Comment by jeff-hykin** [comment]
I'm going to close this but feel free to reopen if there is discussion to be had
