### ISSUE TITLE
Is is possible to extract js into local files?

### ISSUE THREAD

**Issue by ghandic** [jeff-hykin/macro-commander#32]
Wondering if its possible to have files underneath my .vscode folder for my macros eg

```
.vscode
    settings.json
    macros
        injections.js <----- this could be used to allow vscode to know about global variables that can then be used in the scripts 
        snake-to-camel.js
```

Then in macros use (with auto injection)

```js
"macros": {
        "Transform selection: Snake to Camel": [{
            "javascript": "./macros/snake-to-camel.js"
        }],
}
```

or some variation, this way users get intellisense, easier to know what is available to modify in future if type support is added for injections + no need to be escaping characters within an array of strings.

**Comment by jeff-hykin** [comment]
Yeah that definitely would be nice, and I know it's possible because another extension I use pulls in info from a javascript file.

If you make a PR that adds support I'd definitely merge it

**Comment by ghandic** [comment]
What's the extension you're using?

**Comment by ghandic** [comment]
PR here https://github.com/jeff-hykin/macro-commander/pull/33

**Comment by jeff-hykin** [comment]
Haha man that was quick! Thanks for the contribution, I'll get this merged and published as soon as I'm back at my PC.

**Comment by jeff-hykin** [comment]
done v1.4.0 👌
