### ISSUE TITLE
How to use RexEX in replaceALL

### ISSUE THREAD

**Issue by 921j** [jeff-hykin/macro-commander#35]
Hello author, thanks for your excellent extension!
Recently I want to rearrange the comments of some JS files, as follows:
original
`// Settings may also be placed in syntax-specific setting files, for
// example, in Packages/User/Python.sublime-settings for python files.
// Sets the colors used within the text area.
	// The value "auto" will switch between the "light_color_scheme" and
	// "dark_color_scheme" based on the operating system appearance.
// Controls the "color_scheme" when set to "auto"
// Note that the font_face and font_size are overridden in the platform
	// specific settings file, for example, "Preferences (Linux).sublime-settings".
	// Because of this, setting them here will have no effect: you must set them`

to
`// Settings may also be placed in syntax-specific setting files,
// for
// example,
// in Packages/User/Python.sublime-settings for python files.
// Sets the colors used within the text area.
	// The value "auto" will switch between the "light_color_scheme" and
	// "dark_color_scheme" based on the operating system appearance.
// Controls the "color_scheme" when set to "auto"
// Note that the font_face and font_size are overridden in the platform
	// specific settings file,
	// for example,
	// "Preferences (Linux).sublime-settings".
	// Because of this,
	// setting them here will have no effect: you must set them`

The regular expression I use is like this:
search
`( *\/+ *)(\w.*,) ?(\w.*\n)`

replace
`$1$2\n$1$3`

And it has passed the test in RegexBuddy and VSCode, but it doesn't work when written in the configuration file of macro-commander. Either VSCode reports an error or macro-commander reports an error...Using double slash escape, VSCode does not report an error, but it still does not work

![2024-11-14_031125](https://github.com/user-attachments/assets/86fde502-b8fe-4c73-89f0-b9451ff4b870)

How can I write it to make it work?

Sorry,I have never understood VSCode, but I have tested it and found that the following regular statement can be used:
( *\/+ *)(\\\\w.*,) ?(\\\\w.*\\n)
$1$2\\n$1$3

**Comment by jeff-hykin** [comment]
Yeah basically everything needs to be double-escaped.
