### ISSUE TITLE
Allow JavaScript commands to be an array of strings

### ISSUE THREAD

**Issue by t-gehring** [jeff-hykin/macro-commander#4]
Annoyingly, JSON doesn't currently have multiline strings (as far as I can see), but if a js macro gets even slightly complex (e.g. getting user input, doing something with it, then outputting some result) then a single line isn't very convenient. Instead of only checking if a macro step has a `javascript` member of type `string`, you could also check if it's an array, concatenate the entries, and run the result if it's a string. That way a multiline string can be faked as an array of strings, each on a different line.

**Comment by jeff-hykin** [comment]
In my last comment I almost wrote "The best feature would be a good way for getting multiline strings in JSON, but alas". An array of strings is the next best thing. If you make a PR for this I'll merge it in.

**Comment by jeff-hykin** [comment]
This is implemented!
