### ISSUE TITLE
Is there a way to execute key presses?

### ISSUE THREAD

**Issue by neumaneuma** [jeff-hykin/macro-commander#7]
I use the vim extension, so I would like to execute key presses for `Esc` and `o` before running `{ "command": "type",  args": { "text": "some text" } }`. Is that possible?

**Comment by jeff-hykin** [comment]
Hmm I'm not sure.

I'm pretty certain that generic keypresses are not going to be possible, however commands might have specific arguments that can be overridden. If you look at the VS Code Command API they might have some documentation on it.

**Comment by neumaneuma** [comment]
I'll take a look and see if I can find anything. I'll update the issue if I do. Thanks!
