### ISSUE TITLE
Feature request: Option to run autocompleted macro name on space

### ISSUE THREAD

**Issue by PockyBum522** [jeff-hykin/macro-commander#8]
This may be a really stupid request, but I'm programming lisp for AutoCAD all day and I'm very used to the spacebar running something.

I'd love a checkbox to be able to run the currently selected macro with space in the dropdown list, so that for instance, getting to "CommandDown" macro would be:

1. Press keyboard shortcut I've bound to run macro
2. Type cd, having it autohighlight "CommandDown"
3. At this point I can press enter but I'd love to be able to press space, it would mean I could do this entire process entirely with my left hand while moving my hand from the mouse back to the keyboard.

**Comment by PockyBum522** [comment]
As I learn VSCode more, it looks like this might just be a standard menu option. I'll look for a way to implement this request in VSCode itself and report back if I find a way.

**Comment by jeff-hykin** [comment]
Hi, sorry I didn't see this earlier but yes that would be a feature request for the VS Code API. I'm simply calling their api to show the list and the enter-to-confirm is part of VS Code itself. You can probably create a keybinding for it however.

**Comment by PockyBum522** [comment]
Thank you! I'll look into how to do that. Looks like I can do context
sensitive keybindings. Ty
